name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -var="is_github_actions=true" \
                      -var="oidc_role_arn=${{ secrets.AWS_ROLE_ARN }}" \
                      -var="web_identity_token=${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }}"

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform
        terraform apply -auto-approve \
                       -var="is_github_actions=true" \
                       -var="oidc_role_arn=${{ secrets.AWS_ROLE_ARN }}" \
                       -var="web_identity_token=${{ env.AWS_WEB_IDENTITY_TOKEN_FILE }}"